version: '2.1'

services:
  hoohacks19:
    build: .
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    command: >
      bash -c " pip install --upgrade -r requirements.txt
      && cd ./hoohacks
      && python manage.py makemigrations equitunity
      && python manage.py migrate equitunity
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
